name: CI

on:
  push:
    branches:
      -'LR**'
  pull_request:
    branches :
      - main 


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: cd Lab1 && dotnet restore Lab1.Test

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-coverage
          dotnet tool install coverlet.console
      - name: Build
        run: cd Lab1 && dotnet build
      - name: Coverage and test
        run: cd Lab1 && dotnet coverlet Lab1.Test/bin/Debug/net8.0/Lab1.Test.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
